In [150]:
import pandas as pd
import numpy as np 

In [151]:
train_sdss_camera = pd.read_csv("train_sdss_camera.csv")
train_sky_position = pd.read_csv("train_sky_position.csv")

test_sdss_camera = pd.read_csv("test_sdss_camera.csv")
test_sky_position = pd.read_csv("test_sky_position.csv")

In [152]:
train_sdss_camera.head()

id         u         g         r         i         z   run  rerun  camcol  \
0   1  18.45886  17.24552  16.65724  16.27922  16.07007  3712    301       5   
1   2  18.50274  17.50821  17.19507  17.07868  17.08054  3705    301       6   
2   3  18.69451  17.30333  16.48301  16.05570  15.75763  5323    301       5   
3   4  19.34373  18.32701  17.97602  17.82627  17.75770  8108    301       4   
4   5  19.33328  18.13790  17.58180  17.21341  16.99397  4187    301       2   

   field  
0    198  
1    131  
2    140  
3     57  
4    107

In [153]:
train_sdss_camera.shape

(18000, 10)

In [154]:
train_sky_position.head()

id          ra        dec sky_zone object_type
0   3328  201.209696  -0.651584        F        STAR
1  12643         NaN  40.940692        J        STAR
2  10319  187.811300  57.804798        A        STAR
3   3025  197.431052  -0.224783        F      GALAXY
4  16986  329.735546  18.724568        C        STAR

In [155]:
train_sky_position.shape

(18000, 5)

In [156]:
test_sky_position.head()

id          ra        dec sky_zone
0  21652   22.035286   0.632558        J
1  23697  226.973137  26.966352        E
2  29921  240.924725  11.096862        E
3  24247  155.482045  38.598273        D
4  28116  276.679238  22.130552        G

In [157]:
test_sdss_camera.head()

id         u         g         r         i         z   run  rerun  \
0  18001  17.77804  16.40338  15.69551  15.51029  15.41648  6585  301.0   
1  18002  19.17646  18.08458  17.01220  16.35536  15.94323  5115  301.0   
2  18003  18.97518  17.53847  16.98310  16.66949  16.62293  1412  301.0   
3  18004  19.48538  17.55220  16.57528  16.13803  15.76700  2826    NaN   
4  18005  19.09216  17.81581  17.10279  16.66293  16.48639  3704  301.0   

   camcol  field  
0       4    146  
1       3     55  
2       4    294  
3       2    268  
4       6     16

In [158]:
train = pd.merge(train_sdss_camera, train_sky_position, on='id')
train.head()

id         u         g         r         i         z   run  rerun  camcol  \
0   1  18.45886  17.24552  16.65724  16.27922  16.07007  3712    301       5   
1   2  18.50274  17.50821  17.19507  17.07868  17.08054  3705    301       6   
2   3  18.69451  17.30333  16.48301  16.05570  15.75763  5323    301       5   
3   4  19.34373  18.32701  17.97602  17.82627  17.75770  8108    301       4   
4   5  19.33328  18.13790  17.58180  17.21341  16.99397  4187    301       2   

   field          ra        dec sky_zone object_type  
0    198  214.002267  54.488814        I      GALAXY  
1    131  220.688333  53.185834        I        STAR  
2    140  249.118754  12.091483        E      GALAXY  
3     57  330.633293  18.920049        C        STAR  
4    107         NaN  -0.813704        C      GALAXY

In [159]:
test = pd.merge(test_sdss_camera, test_sky_position, on='id')
test.head()

id         u         g         r         i         z   run  rerun  \
0  18001  17.77804  16.40338  15.69551  15.51029  15.41648  6585  301.0   
1  18002  19.17646  18.08458  17.01220  16.35536  15.94323  5115  301.0   
2  18003  18.97518  17.53847  16.98310  16.66949  16.62293  1412  301.0   
3  18004  19.48538  17.55220  16.57528  16.13803  15.76700  2826    NaN   
4  18005  19.09216  17.81581  17.10279  16.66293  16.48639  3704  301.0   

   camcol  field          ra        dec sky_zone  
0       4    146  105.295891  29.857393        H  
1       3     55  178.795262  27.223414        F  
2       4    294  226.759800  61.228082        I  
3       2    268  177.735503  56.820679        A  
4       6     16  132.988928  30.463367        B

In [160]:
(train.isnull().sum()/train.shape[0])*100

id             0.000000
u              1.283333
g              1.283333
r              1.283333
i              1.283333
z              1.283333
run            0.000000
rerun          0.000000
camcol         0.000000
field          0.000000
ra             4.777778
dec            0.000000
sky_zone       0.000000
object_type    0.000000
dtype: float64

In [161]:
# Dropping all rows with missing values 
train = train.dropna()
train.isnull().sum()

id             0
u              0
g              0
r              0
i              0
z              0
run            0
rerun          0
camcol         0
field          0
ra             0
dec            0
sky_zone       0
object_type    0
dtype: int64

In [162]:
np.unique(train["sky_zone"])

array(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'], dtype=object)

In [163]:
fact = pd.factorize(train["sky_zone"])
train["sky_zone"] = fact[0]
fact[1]

Index(['I', 'E', 'C', 'J', 'A', 'D', 'F', 'H', 'B', 'G'], dtype='object')

In [164]:
factor = pd.factorize(train["object_type"])
train["object_type"] = factor[0]
defs = factor[1]

In [165]:
factor[1]

Index(['GALAXY', 'STAR', 'QUASAR'], dtype='object')

In [166]:
train.head()

id         u         g         r         i         z   run  rerun  camcol  \
0   1  18.45886  17.24552  16.65724  16.27922  16.07007  3712    301       5   
1   2  18.50274  17.50821  17.19507  17.07868  17.08054  3705    301       6   
2   3  18.69451  17.30333  16.48301  16.05570  15.75763  5323    301       5   
3   4  19.34373  18.32701  17.97602  17.82627  17.75770  8108    301       4   
5   6  18.12876  17.20399  16.86027  16.57519  16.44839  4858    301       1   

   field          ra        dec  sky_zone  object_type  
0    198  214.002267  54.488814         0            0  
1    131  220.688333  53.185834         0            1  
2    140  249.118754  12.091483         1            0  
3     57  330.633293  18.920049         2            1  
5    461   16.005079  -0.855938         3            0

In [167]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 16924 entries, 0 to 17999
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   id           16924 non-null  int64  
 1   u            16924 non-null  float64
 2   g            16924 non-null  float64
 3   r            16924 non-null  float64
 4   i            16924 non-null  float64
 5   z            16924 non-null  float64
 6   run          16924 non-null  int64  
 7   rerun        16924 non-null  int64  
 8   camcol       16924 non-null  int64  
 9   field        16924 non-null  int64  
 10  ra           16924 non-null  float64
 11  dec          16924 non-null  float64
 12  sky_zone     16924 non-null  int64  
 13  object_type  16924 non-null  int64  
dtypes: float64(7), int64(7)
memory usage: 1.9 MB


In [168]:
from sklearn.model_selection import train_test_split

X = train.drop(["object_type", "id"], axis=1)
y = train['object_type']
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=42)

In [169]:
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

clf = RandomForestClassifier(n_estimators = 25, criterion = "entropy", random_state=42)
clf.fit(X_train, y_train)
preds = clf.predict(X_test)
accuracy_score(preds, y_test)

0.9092162268609689

In [170]:
np.unique(preds)

array([0, 1, 2])

In [171]:
test.isnull().sum()

id             0
u              0
g              0
r              0
i              0
z              0
run            0
rerun       1200
camcol         0
field          0
ra           579
dec            0
sky_zone       0
dtype: int64

In [172]:
test["rerun"] = test["rerun"].fillna(301)
test["ra"] = test["ra"].fillna(np.mean(test["ra"]))

In [173]:
test.isnull().sum()


id          0
u           0
g           0
r           0
i           0
z           0
run         0
rerun       0
camcol      0
field       0
ra          0
dec         0
sky_zone    0
dtype: int64

In [174]:
np.unique(test["sky_zone"])

array(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'], dtype=object)

In [175]:
pd.factorize(test["sky_zone"])

(array([0, 1, 2, ..., 5, 7, 4]),
 Index(['H', 'F', 'I', 'A', 'B', 'J', 'E', 'G', 'C', 'D'], dtype='object'))

In [176]:
fact

(array([0, 0, 1, ..., 9, 8, 4]),
 Index(['I', 'E', 'C', 'J', 'A', 'D', 'F', 'H', 'B', 'G'], dtype='object'))

In [177]:
fact[1]

Index(['I', 'E', 'C', 'J', 'A', 'D', 'F', 'H', 'B', 'G'], dtype='object')

In [178]:
values = list(range(0,10))
values

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [179]:
dict(zip(fact[1], values))

{'I': 0,
 'E': 1,
 'C': 2,
 'J': 3,
 'A': 4,
 'D': 5,
 'F': 6,
 'H': 7,
 'B': 8,
 'G': 9}

In [180]:
test['sky_zone'] = test['sky_zone'].replace(dict(zip(fact[1], values)))

In [183]:
ids = test["id"].tolist()
test = test.drop("id", axis=1)

In [184]:
test = scaler.transform(test)

In [185]:
test_preds = clf.predict(test)

In [186]:
np.unique(test_preds)

array([0, 1, 2])

In [187]:
test_preds

array([1, 0, 1, ..., 0, 1, 1])

In [188]:
defs

Index(['GALAXY', 'STAR', 'QUASAR'], dtype='object')

In [189]:
dict1 = dict(zip(range(3), defs))

In [190]:
test_preds_as_str = [dict1[pred] for pred in test_preds]

In [197]:
pd_dict = {'id': ids, 'object_type':test_preds_as_str}
pd_dict

{'id': [18001,
  18002,
  18003,
  18004,
  18005,
  18006,
  18007,
  18008,
  18009,
  18010,
  18011,
  18012,
  18013,
  18014,
  18015,
  18016,
  18017,
  18018,
  18019,
  18020,
  18021,
  18022,
  18023,
  18024,
  18025,
  18026,
  18027,
  18028,
  18029,
  18030,
  18031,
  18032,
  18033,
  18034,
  18035,
  18036,
  18037,
  18038,
  18039,
  18040,
  18041,
  18042,
  18043,
  18044,
  18045,
  18046,
  18047,
  18048,
  18049,
  18050,
  18051,
  18052,
  18053,
  18054,
  18055,
  18056,
  18057,
  18058,
  18059,
  18060,
  18061,
  18062,
  18063,
  18064,
  18065,
  18066,
  18067,
  18068,
  18069,
  18070,
  18071,
  18072,
  18073,
  18074,
  18075,
  18076,
  18077,
  18078,
  18079,
  18080,
  18081,
  18082,
  18083,
  18084,
  18085,
  18086,
  18087,
  18088,
  18089,
  18090,
  18091,
  18092,
  18093,
  18094,
  18095,
  18096,
  18097,
  18098,
  18099,
  18100,
  18101,
  18102,
  18103,
  18104,
  18105,
  18106,
  18107,
  18108,
  18109,
  18110,
  18

In [199]:
submission = pd.DataFrame(pd_dict)
# submission

id object_type
0      18001        STAR
1      18002      GALAXY
2      18003        STAR
3      18004      GALAXY
4      18005      GALAXY
...      ...         ...
11995  29996        STAR
11996  29997      GALAXY
11997  29998      GALAXY
11998  29999        STAR
11999  30000        STAR

[12000 rows x 2 columns]